### ISSUE TITLE
Invalid Parameter

### ISSUE THREAD

**Issue by cap20** [arpit999bicubic/YoutubeDownload#3]
I'm getting the following error in your project, can you please rectify them i need it::

W/Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
W/System.err: com.commit451.youtubeextractor.YouTubeExtractionException: Status: fail
    Reason: Invalid parameters.
    Error code: 2
        at com.commit451.youtubeextractor.YouTubeBodyConverter.convert(YouTubeBodyConverter.java:86)
        at com.commit451.youtubeextractor.YouTubeBodyConverter.convert(YouTubeBodyConverter.java:24)
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:116)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
W/System.err:     at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:106)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by ThayalanGR** [comment]
Same problem !

**Comment by arpit999** [comment]
Try **Method 2** on this [answer ](https://stackoverflow.com/questions/7203047/code-for-download-video-from-youtube-on-java-android/40479466#40479466)it will work.
